fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    download_file: https://github.com/opentable/puppet-download_file
    powershell: https://github.com/joshcooper/puppetlabs-powershell
  symlinks:
    iis_rewrite: "#{source_dir}"
